### ISSUE TITLE
MRO - Add PM Information

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3SRel2.0#133]
Please add PM INFORMATION, after EQUIPMENT INFORMATION, before LABOUR AND PARTS.

![image](https://cloud.githubusercontent.com/assets/5666297/10203772/0314a6d6-6786-11e5-9240-edc60f0db10a.png)

PM fold would look like the following:

![image](https://cloud.githubusercontent.com/assets/5666297/10205031/fa89ef7e-678c-11e5-9d39-60fc843ea016.png)

Logic is the following, search for any RO for that unit in the past with the SYSTEM-ASSEMBLY codes equal to the ones in the table, once found:
- Show the RO date as LAST PM DATE
- TODAY - RO date will be DAYS SINCE LAST PM
- Get Readings based on the RO record

** Only search ROs from the last 16 months (in order to improve performance)
** Note that not all units will have all the values found
** Please be careful for these extra SQL not to add much more time to the RO loading process.
** In the future we may have to add more PM codes on the grid, so make it flexible.

**Comment by d3ssupport** [comment]
Ok we will work on it. 



Sent from my Samsung Galaxy smartphone.

Please add PM INFORMATION, after EQUIPMENT INFORMATION, before LABOUR AND PARTS. PM fold would look like the following: Logic is the following, search for any RO for that unit in the past with the SYSTEM-ASSEMBLY codes equal to the ones in the table, once found: Show the RO date as LAST PM DATE TODAY - RO date will be DAYS SINCE LAST PM Get Readings based on the RO record ** Only search ROs from the last 16 months (in order to improve performance) ** Note that not all units will have all the values found ** Please be careful for these extra SQL not to add much more time to the RO loading process. ** In the future we may have to add more PM codes on the grid, so make it flexible. —Reply to this email directly or view it on GitHub.

**Comment by giovanicani** [comment]
deferred.

**Comment by giovanicani** [comment]
I am moving PM data from EMDECS into TCS/D3S.

**Comment by giovanicani** [comment]
this will be tracked via another ticket.
