### ISSUE TITLE
RO Error sending to EMDECS - Notes needs to be SUBSTR.

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3SRel2.0#138]
See error below due to string size. Please limit notes being sent to EMDECS on the labour line, max allowed when sending into EMDECS is 1000. Also please make the same substring on the WO Notes and part notes.

![screen shot 2015-10-05 at 2 26 28 pm](https://cloud.githubusercontent.com/assets/5666297/10289597/1f90b6b6-6b6d-11e5-8f19-99e839f54578.png)

**Comment by d3ssupport** [comment]
Acknowledge.. 

Thanks

Sent from my Samsung Galaxy smartphone.

See error below due to string size. Please limit notes being sent to EMDECS on the labour line, max allowed when sending into EMDECS is 1000. Also please make the same substring on the WO Notes and part notes. —Reply to this email directly or view it on GitHub.

**Comment by giovanicani** [comment]
API Change, already done. Ready to be tested.

**Comment by giovanicani** [comment]
works. thanks!
