### ISSUE TITLE
MRO - More tweaks on barcode

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3SRel2.0#148]
As per screen shot below, please make the following adjustments:

1. Move the barcode part reader to the left so that mechanic can see the list of parts
2. Add in bold the labour description currently having the part added to it. Please see verbiage change.

![image](https://cloud.githubusercontent.com/assets/5666297/10516499/90a1f82c-7326-11e5-8cd1-ca65663cc36d.png)

**Comment by d3ssupport** [comment]
Acknowledge 

Thanks
D3S Team. 



As per screen shot below, please make the following adjustments: Move the barcode part reader to the left so that mechanic can see the list of parts Add in bold the labour description currently having the part added to it. Please see verbiage change. —Reply to this email directly or view it on GitHub.

**Comment by d3sqa** [comment]
The scan barcode window has been moved to the left side and labour description has been added to it in bold. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
works. thanks!
